import psycopg2
import configparser
from shop_api import all_data
from normalize_api2 import normalize_data_1


#CARGA EN POSTGRE SQL
# Conéctate a la base de datos PostgreSQL local
config = configparser.ConfigParser()
config.read('config.ini')

conn = psycopg2.connect(
    dbname=config['SQL']['dbname'], # Nombre de la base de datos
    user=config['SQL']['user'], # Nombre de usuario de PostgreSQL
    password=config['SQL']['password'], # Contraseña de PostgreSQL
    host=config['SQL']['host']  # Dirección del servidor (en este caso, localhost)
)


#CREAR TABLA EN POSTGRE
table_name = 'shopify_orders'

create_table_query = f"""
CREATE TABLE IF NOT EXISTS {table_name} (
id INT,
admin_graphql_api_id TEXT,
app_id INT,
browser_ip TEXT,
buyer_accepts_marketing BOOLEAN,
cancel_reason TEXT,
cancelled_at TIMESTAMP,
cart_token TEXT,
checkout_id BIGINT,
checkout_token TEXT,
closed_at TIMESTAMP,
company TEXT,
confirmation_number TEXT,
confirmed BOOLEAN,
created_at TIMESTAMP,
currency TEXT,
current_subtotal_price DECIMAL(10, 2),
current_total_additional_fees_set TEXT,
current_total_discounts DECIMAL(10, 2),
current_total_duties_set TEXT,
current_total_price DECIMAL(10, 2),
current_total_tax DECIMAL(10, 2),
customer_locale TEXT,
device_id TEXT,
discount_codes TEXT[],
estimated_taxes BOOLEAN,
financial_status TEXT,
fulfillment_status TEXT,
landing_site TEXT,
landing_site_ref TEXT,
location_id BIGINT,
merchant_of_record_app_id INT,
name TEXT,
note TEXT,
note_attributes TEXT[],
number INT,
order_number INT,
order_status_url TEXT,
original_total_additional_fees_set TEXT,
original_total_duties_set TEXT,
payment_gateway_names TEXT[],
po_number TEXT,
presentment_currency TEXT,
processed_at TIMESTAMP,
reference TEXT,
referring_site TEXT,
source_identifier TEXT,
source_name TEXT,
source_url TEXT,
subtotal_price DECIMAL(10, 2),
tags TEXT,
tax_exempt BOOLEAN,
taxes_included BOOLEAN,
test BOOLEAN,
token TEXT,
total_discounts DECIMAL(10, 2),
total_line_items_price DECIMAL(10, 2),
total_outstanding DECIMAL(10, 2),
total_price DECIMAL(10, 2),
total_tax DECIMAL(10, 2),
total_tip_received DECIMAL(10, 2),
total_weight INT,
updated_at TIMESTAMP,
user_id BIGINT,
discount_applications TEXT[],
fulfillments TEXT[],
payment_terms TEXT,
refunds TEXT[],
client_details_accept_language TEXT,
client_details_browser_height INT,
client_details_browser_ip TEXT,
client_details_browser_width INT,
client_details_session_hash TEXT,
client_details_user_agent TEXT,
current_subtotal_price_set_shop_money_amount DECIMAL(10, 2),
current_subtotal_price_set_shop_money_currency_code TEXT,
current_subtotal_price_set_presentment_money_amount DECIMAL(10, 2),
current_subtotal_price_set_presentment_money_currency_code TEXT,
current_total_discounts_set_shop_money_amount DECIMAL(10, 2),
current_total_discounts_set_shop_money_currency_code TEXT,
current_total_discounts_set_presentment_money_amount DECIMAL(10, 2),
current_total_discounts_set_presentment_money_currency_code TEXT,
current_total_price_set_shop_money_amount DECIMAL(10, 2),
current_total_price_set_shop_money_currency_code TEXT,
current_total_price_set_presentment_money_amount DECIMAL(10, 2),
current_total_price_set_presentment_money_currency_code TEXT,
current_total_tax_set_shop_money_amount DECIMAL(10, 2),
current_total_tax_set_shop_money_currency_code TEXT,
current_total_tax_set_presentment_money_amount DECIMAL(10, 2),
current_total_tax_set_presentment_money_currency_code TEXT,
subtotal_price_set_shop_money_amount DECIMAL(10, 2),
subtotal_price_set_shop_money_currency_code TEXT,
subtotal_price_set_presentment_money_amount DECIMAL(10, 2),
subtotal_price_set_presentment_money_currency_code TEXT,
total_discounts_set_shop_money_amount DECIMAL(10, 2),
total_discounts_set_shop_money_currency_code TEXT,
total_discounts_set_presentment_money_amount DECIMAL(10, 2),
total_discounts_set_presentment_money_currency_code TEXT,
total_line_items_price_set_shop_money_amount DECIMAL(10, 2),
total_line_items_price_set_shop_money_currency_code TEXT,
total_line_items_price_set_presentment_money_amount DECIMAL(10, 2),
total_line_items_price_set_presentment_money_currency_code TEXT,
total_price_set_shop_money_amount DECIMAL(10, 2),
total_price_set_shop_money_currency_code TEXT,
total_price_set_presentment_money_amount DECIMAL(10, 2),
total_price_set_presentment_money_currency_code TEXT,
total_shipping_price_set_shop_money_amount DECIMAL(10, 2),
total_shipping_price_set_shop_money_currency_code TEXT,
total_shipping_price_set_presentment_money_amount DECIMAL(10, 2),
total_shipping_price_set_presentment_money_currency_code TEXT,
total_tax_set_shop_money_amount DECIMAL(10, 2),
total_tax_set_shop_money_currency_code TEXT,
total_tax_set_presentment_money_amount DECIMAL(10, 2),
total_tax_set_presentment_money_currency_code TEXT,
billing_address_province TEXT,
billing_address_country TEXT,
billing_address_latitude DECIMAL(10, 6),
billing_address_longitude DECIMAL(10, 6),
billing_address_country_code TEXT,
billing_address_province_code TEXT,
customer_id BIGINT,
customer_accepts_marketing BOOLEAN,
customer_created_at TIMESTAMP,
customer_updated_at TIMESTAMP,
customer_state TEXT,
customer_note TEXT,
customer_verified_email BOOLEAN,
customer_multipass_identifier TEXT,
customer_tax_exempt BOOLEAN,
customer_email_marketing_consent_state TEXT,
customer_email_marketing_consent_opt_in_level TEXT,
customer_email_marketing_consent_consent_updated_at TIMESTAMP,
customer_sms_marketing_consent TEXT,
customer_tags TEXT,
customer_currency TEXT,
customer_accepts_marketing_updated_at TIMESTAMP,
customer_marketing_opt_in_level TEXT,
customer_tax_exemptions TEXT[],
customer_admin_graphql_api_id TEXT,
customer_default_address_id BIGINT,
customer_default_address_customer_id BIGINT,
customer_default_address_company TEXT,
customer_default_address_province TEXT,
customer_default_address_country TEXT,
customer_default_address_province_code TEXT,
customer_default_address_country_code TEXT,
customer_default_address_country_name TEXT,
customer_default_address_default BOOLEAN,
shipping_address_province TEXT,
shipping_address_country TEXT,
shipping_address_company TEXT,
shipping_address_country_code TEXT,
shipping_address_province_code TEXT,
level_2_0_price NUMERIC,
level_2_0_rate NUMERIC,
level_2_0_title TEXT,
level_2_0_channel_liable BOOLEAN,
level_2_0_price_set_shop_money_amount NUMERIC,
level_2_0_price_set_shop_money_currency_code TEXT,
level_2_0_price_set_presentment_money_amount NUMERIC,
level_2_0_price_set_presentment_money_currency_code TEXT,
level_2_1_id BIGINT,
level_2_1_admin_graphql_api_id TEXT,
level_2_1_attributed_staffs TEXT[],
level_2_1_fulfillable_quantity INT,
level_2_1_fulfillment_service TEXT,
level_2_1_fulfillment_status TEXT,
level_2_1_gift_card BOOLEAN,
level_2_1_grams INT,
level_2_1_name TEXT,
level_2_1_price NUMERIC,
level_2_1_product_exists BOOLEAN,
level_2_1_product_id BIGINT,
level_2_1_properties TEXT[],
level_2_1_quantity INT,
level_2_1_requires_shipping BOOLEAN,
level_2_1_sku TEXT,
level_2_1_taxable BOOLEAN,
level_2_1_title TEXT,
level_2_1_total_discount NUMERIC,
level_2_1_variant_id BIGINT,
level_2_1_variant_inventory_management TEXT,
level_2_1_variant_title TEXT,
level_2_1_vendor TEXT,
level_2_1_duties TEXT[],
level_2_1_discount_allocations TEXT[],
level_2_1_price_set_shop_money_amount NUMERIC,
level_2_1_price_set_shop_money_currency_code TEXT,
level_2_1_price_set_presentment_money_amount NUMERIC,
level_2_1_price_set_presentment_money_currency_code TEXT,
level_2_1_total_discount_set_shop_money_amount NUMERIC,
level_2_1_total_discount_set_shop_money_currency_code TEXT,
level_2_1_total_discount_set_presentment_money_amount NUMERIC,
level_2_1_total_discount_set_presentment_money_currency_code TEXT,
level_2_2_id BIGINT,
level_2_2_carrier_identifier TEXT,
level_2_2_code TEXT,
level_2_2_discounted_price NUMERIC,
level_2_2_phone TEXT,
level_2_2_price NUMERIC,
level_2_2_requested_fulfillment_service_id BIGINT,
level_2_2_source TEXT,
level_2_2_title TEXT,
level_2_2_tax_lines TEXT[],
level_2_2_discount_allocations TEXT[],
level_2_2_discounted_price_set_shop_money_amount NUMERIC,
level_2_2_discounted_price_set_shop_money_currency_code TEXT,
level_2_2_discounted_price_set_presentment_money_amount NUMERIC,
level_2_2_discounted_price_set_presentment_money_currency_code TEXT,
level_2_2_price_set_shop_money_amount NUMERIC,
level_2_2_price_set_shop_money_currency_code TEXT,
level_2_2_price_set_presentment_money_amount NUMERIC,
level_2_2_price_set_presentment_money_currency_code TEXT
    );
"""

cur = conn.cursor()
cur.execute(create_table_query)
conn.commit()


# Convierte el DataFrame en una lista de tuplas para insertar en la base de datos
normalize= normalize_data_1(all_data)
data_to_insert = normalize.values.tolist()

# Construye la consulta de inserción
insert_query = f"INSERT INTO {table_name} VALUES ({', '.join(['%s' for _ in range(len(normalize.columns))])})"

# Inserta los datos en la tabla
cur.executemany(insert_query, data_to_insert)
conn.commit()

# Cierra la conexión a la base de datos
conn.close()

