[theme]

# Primary accent for interactive elements
primaryColor = '#153827'
#'#FFB8F4'
#'#E694FF'

# Background color for the main content area
backgroundColor = '#153827'
#'#7733FF'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#DDC395'
#'#0083B8'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"